### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Benisland35** [rsusik/screenpen#11]
Hello,
I successfully installed Python 3.12 on Windows 10, PyQt5 is present, I followed your instructions to install screenpen 0.2.0. There was no error message and then type screenpen in command prompt, but nothing happens, except normal return to command prompt for next command. There was no error message, no successful message and overall no screenpen tools displayed.
What's wrong?

Thanks in advance for your reply.

**Comment by rsusik** [comment]
Can you check if `python -m screenpen` or `python3 -m screenpen` helps?
Do you see `PyQt5 is installed.` message when running?

**Comment by rsusik** [comment]
Closing as there is no response

**Comment by Benisland35** [comment]
Hi Robert,

You closed the issue because you didn't receive an answer, but I  replied
you on the 21th October. Please check your email or spam folder.
I forward my reply to you here after.

Thanks.

**Comment by rsusik** [comment]
Please answer here. Nothing is in my inbox or spam folder. Reopening
