### ISSUE TITLE
Unable to run Screenpen in windows

### ISSUE THREAD

**Issue by enthusedcoder** [rsusik/screenpen#18]
Hello.  So, the issue I am facing seems to be the same that is detailed in issue #11 : I am running python 3.12.3 on Windows 11 and have installed screenpen using pip, as detailed in the instructions on the project's main page.  However, nothing happens when I run screenpen after installing it with pip.  I do see the process briefly launch in task manager, but then it immediately closes.  Looking over your recommendations in issue #11 , I ran "python -m screenpen" and received the following output:

```
python -m screenpen
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "C:\Users\john\AppData\Local\Programs\Python\Python312\Lib\site-packages\screenpen\__init__.py", line 1, in <module>
    from screenpen.screenpen import main
  File "C:\Users\john\AppData\Local\Programs\Python\Python312\Lib\site-packages\screenpen\screenpen.py", line 10, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

So, looking at the error message, I figured "oh, so maybe there is a module named "pkg_resources" that I can install using pip that will resolve this issue," so I attempt to do just that.  However, pip was not able to find a module with that name, it would seem:

```
ERROR: Could not find a version that satisfies the requirement pkg_resources (from versions: none)
ERROR: No matching distribution found for pkg_resources
```

 I hope this additional information will help you resolve whatever issues is preventing screenpen from running on windows.  Please let me know if you need anything else from me.

**Comment by rsusik** [comment]
It seems you have corrupted setuptools or do not have it at all. Please check this solution: https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources

If you don't have setuptools, `pip install setuptools` may also not work and may require you to download and reinstall Python.

Btw. how did you install this Python instance on your system?
