### ISSUE TITLE
Can't open screenpen

### ISSUE THREAD

**Issue by mhalano** [rsusik/screenpen#4]
Hi,

I'm trying to open the screenpen but I get this error message instead of the window to select the screen. I'm using Ubuntu 22.04 LTS with X11 and Python 3.
![image](https://user-images.githubusercontent.com/6025031/168260626-f4af40ed-a7c6-4e5d-acf4-17df8c046de6.png)

**Comment by rsusik** [comment]
Hi @mhalano,

Qt requires to have mentioned module installed in your system. Please install it:

`sudo apt-get install appmenu-gtk2-module appmenu-gtk3-module`

(more: https://askubuntu.com/questions/1074926/failed-to-load-module-appmenu-gtk-module-canberra-gtk-module)

Let me know if it helps.

Cheers,
Robert

**Comment by mhalano** [comment]
Hi @rsusik,

I installed both packages as requested and still doesn't work. Any more tips?

**Comment by mhalano** [comment]
The updated error after install both packages and canberra mentioned in the link. I think it looks pretty the same.
![image](https://user-images.githubusercontent.com/6025031/168266749-da495895-275e-439d-86da-9638201144e6.png)

**Comment by rsusik** [comment]
Thanks, I fixed it now. Please update the program and let me know if it works now on your side:

`pip install screenpen==0.1.12`

**Comment by mhalano** [comment]
I think it doesn't work yet.
![image](https://user-images.githubusercontent.com/6025031/168271632-77a3dc2b-2356-4b2e-9600-126fce4aeff6.png)

**Comment by rsusik** [comment]
Please check again: `pip install screenpen==0.1.13`

**Comment by mhalano** [comment]
Thanks. Now opens correctly. Doesn't write in the screen, but at least open. :) I will open a new bug to keep separation by problem. Thank you!

**Comment by rsusik** [comment]
Thanks!

**Comment by DrearyWillow** [comment]
I'm having a similar issue in 0.1.16 even after installing the packages mentioned above. Any advice?
![image](https://user-images.githubusercontent.com/108599378/235331456-1962bc9f-7c82-45ec-9dc3-fbb76756fe24.png)

**Comment by rsusik** [comment]
It will not work with PySide. Install PyQt5:

`pip install PyQt5 PyQt5-Qt5 PyQt5-sip`

**Comment by DrearyWillow** [comment]
Thanks for the reply. I installed those packages and restarted my computer to be extra sure, but I'm still getting the same error. Sorry if I'm making another basic mistake.
![image](https://user-images.githubusercontent.com/108599378/235381221-0e00a300-692f-4f88-9472-4920c79a56b8.png)

**Comment by rsusik** [comment]
Can you provide me with the output from `pip freeze`, `uname -a`, and `python -V` so I can reproduce your error?

**Comment by DrearyWillow** [comment]
uname -a:
```
Linux minty 5.15.0-71-generic #78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

python -V:
```
Python 3.10.6
```
<details>
<summary>
pip freeze:
</summary>

```ruby
anipy-cli==2.7.19
appdirs==1.4.4
apsw==3.36.0.post1
apt-clone==0.2.1
apturl==0.5.2
args==0.1.0
attrs==21.2.0
babelfish==0.6.0
backcall==0.2.0
bandcamp-downloader==0.0.13
beautifulsoup4==4.10.0
beniget==0.4.1
better-ffmpeg-progress==2.1.0
blinker==1.4
Brlapi==0.8.3
Brotli==1.0.9
certifi==2020.6.20
chardet==4.0.0
click==8.0.3
clint==0.5.1
colorama==0.4.4
coloredlogs==7.3
command-not-found==0.3
configobj==5.0.6
cryptography==3.4.8
css-parser==1.0.7
cssselect==1.1.0
cssutils==1.0.2
cupshelpers==1.0
cycler==0.11.0
dacite==1.8.0
dbus-python==1.2.18
decorator==4.4.2
defer==1.0.6
demjson3==3.0.6
distro==1.7.0
dnspython==2.1.0
docopt==0.6.2
evdev==1.4.0
eyeD3==0.8.10
feedparser==6.0.8
ffmpeg-python==0.2.0
filelock==3.6.0
fonttools==4.29.1
fs==2.4.12
future==0.18.3
gast==0.5.2
grpcio==1.30.2
guessit==3.7.1
html2text==2020.1.16
html5-parser==0.4.10
html5lib==1.1
httplib2==0.20.2
humanfriendly==10.0
idna==3.3
ifaddr==0.1.7
imageio==2.27.0
imageio-ffmpeg==0.4.8
IMDbPY==2021.4.18
img2pdf==0.4.2
importlib-metadata==4.6.4
ipython==7.31.1
iso8601==1.1.0
jedi==0.18.0
jeepney==0.7.1
keyring==23.5.0
kiwisolver==1.3.2
launchpadlib==1.10.16
lazr.restfulclient==0.14.4
lazr.uri==1.0.6
louis==3.20.0
lxml==4.8.0
lz4==3.1.3+dfsg
m3u8==3.4.0
macaroonbakery==1.3.1
Mako==1.1.3
Markdown==3.3.6
MarkupSafe==2.0.1
matplotlib==3.5.1
matplotlib-inline==0.1.3
mechanize==0.4.7
mock==5.0.1
more-itertools==8.10.0
moviepy==1.0.3
mpmath==0.0.0
msgpack==1.0.3
mutagen==1.46.0
nemo-emblems==5.6.0
nemo-media-columns==5.6.0
netaddr==0.8.0
netifaces==0.11.0
numpy==1.21.5
oauthlib==3.2.0
ocrmypdf==13.4.0+dfsg
onboard==1.4.1
packaging==21.3
PAM==0.4.2
parso==0.8.1
pathvalidate==2.5.0
pdfminer.six===-VERSION-
pexpect==4.8.0
pickleshare==0.7.5
pikepdf==5.0.1+dfsg
Pillow==9.0.1
pluggy==0.13.0
ply==3.11
proglog==0.1.10
prompt-toolkit==3.0.28
protobuf==3.12.4
psutil==5.8.0
ptyprocess==0.7.0
py7zr==0.11.3+dfsg
pycairo==1.20.1
pychm==0.8.6
pycryptodomex==3.11.0
pycups==2.0.1
pycurl==7.44.1
pyelftools==0.27
Pygments==2.11.2
PyGObject==3.42.1
PyICU==2.8.1
pyinotify==0.9.6
PyJWT==2.3.0
pymacaroons==0.13.0
pymediainfo==5.0.3
PyNaCl==1.5.0
pyparsing==2.4.7
pyparted==3.11.7
PyPDF2==1.26.0
pypresence==4.2.1
PyQt5==5.15.6
PyQt5-Qt5==5.15.2
PyQt5-sip==12.9.1
PyQtWebEngine==5.15.5
pyRFC3339==1.1
PySide6==6.2.0
python-apt==2.4.0+ubuntu1
python-dateutil==2.8.2
python-debian===0.1.43ubuntu1
python-gnupg==0.4.8
python-Levenshtein==0.12.2
python-magic==0.4.24
python-mpv==1.0.3
python-xlib==0.29
pythran==0.10.0
pytz==2022.1
pyxattr==0.7.2
pyxdg==0.27
PyYAML==5.4.1
rebulk==3.2.0
regex==2021.11.10
reportlab==3.6.8
repoze.lru==0.7
requests==2.25.1
requests-file==1.5.1
requests-toolbelt==0.9.1
Routes==2.5.1
scdl==2.7.3
scipy==1.8.0
screen-resolution-extra==0.0.0
screenpen==0.1.16
SecretStorage==3.3.1
selenium==3.141.0
setproctitle==1.2.2
sgmllib3k==1.0.0
shiboken6==6.2.0
six==1.16.0
soundcloud-v2==1.3.1
soupsieve==2.3.1
stopit==1.1.2
sympy==1.9
systemd-python==234
termcolor==2.2.0
texttable==1.6.4
tinycss2==1.1.1
tldextract==3.1.2
tqdm==4.57.0
traitlets==5.1.1
ubuntu-drivers-common==0.0.0
ufoLib2==0.13.1
ufw==0.36.1
ulauncher==5.15.1
unicode-slugify==0.1.5
unicodedata2==14.0.0
Unidecode==1.3.3
urllib3==1.26.7
wadllib==1.3.6
wcwidth==0.2.5
webencodings==0.5.1
WebOb==1.8.6
websocket-client==1.2.3
websockets==10.4
xdg==5
xkit==0.0.0
xlrd==1.2.0
youtube-dl==2021.12.17
yt-dlp==2023.3.4
zeroconf==0.38.3
zipp==1.0.0
```
</details>

**Comment by rsusik** [comment]
Hi, thanks. I was able to reproduce the error. It looks like there is a conflict between `PyQt` and `PySide`. Please remove `PySide6,` and the conflict should be resolved:

`pip uninstall PySide6`

It looks like `PySide` should not be installed alongside the `PyQt`. Hopefully, it helps.
I will handle this case in the next version, but currently, I'm snowed under with other work.

**Comment by DrearyWillow** [comment]
This worked! Thanks so much for taking the time to help me out while you're busy. :)

**Comment by rsusik** [comment]
Thanks for confirming :)
