### ISSUE TITLE
Can't draw on the screen

### ISSUE THREAD

**Issue by mhalano** [rsusik/screenpen#5]
After I select a tool and a color, I can't draw over screen. I get spammed in the console by messages like these.
![image](https://user-images.githubusercontent.com/6025031/168274574-d4e867db-09b1-4e96-bb49-613e0acc0357.png)

**Comment by rsusik** [comment]
Thanks, It will be easy to fix. Somehow Qt library has problems with floats with your configuration. I will update shortly.

**Comment by rsusik** [comment]
Updated. Please let me know if it works: `pip install screenpen==0.1.14`

**Comment by mhalano** [comment]
Working flawlessly. :)

**Comment by rsusik** [comment]
Thank you for your time and patience, Cheers
