### ISSUE TITLE
it's not transparent - my desktop is hidden

### ISSUE THREAD

**Issue by sl5net** [rsusik/screenpen#6]
i did:

```sh
pip install screenpen
python -m screenpen
```
![Screenshot_20230113_212351](https://user-images.githubusercontent.com/5634759/212412509-bd3a7576-24b3-41dc-8680-156c626118b1.jpg)

in other words i dont see my desktop

during installation i also got some WARNING:
```sh
  WARNING: The scripts f2py, f2py3 and f2py3.10 are installed in '/home/seeh/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts fonttools, pyftmerge, pyftsubset and ttx are installed in '/home/seeh/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed contourpy-1.0.7 cycler-0.11.0 fonttools-4.38.0 kiwisolver-1.4.4 matplotlib-3.6.3 numpy-1.24.1 python-dateutil-2.8.2 screenpen-0.1.14
```

my System:
```matlab
Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.15.0-57-generic (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 3700X 8-Core Processor
Memory: 31,3 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
```

**Comment by rsusik** [comment]
Thanks for reporting this. I haven't tested it on Kubuntu yet (I will do it soon), but meanwhile, could you confirm you tried the below button?

![image](https://user-images.githubusercontent.com/19404835/212413647-7fae8ad5-0f6d-45ab-a426-aa5dd9d1fc2f.png)

**Comment by sl5net** [comment]
> Thanks for reporting this. I haven't tested it on Kubuntu yet (I will do it soon), but meanwhile, could you confirm you tried the below button?
> 
> ![image](https://user-images.githubusercontent.com/19404835/212413647-7fae8ad5-0f6d-45ab-a426-aa5dd9d1fc2f.png)

i have tried. it not helps to make my screen visible

**Comment by rsusik** [comment]
It should work now. Please update the screenpen:

`pip install screenpen -U`

Let me know if it works now on your side.

**Comment by rsusik** [comment]
No response. Closing.

**Comment by pawandeepthind** [comment]
Does not work for me. I am trying this on Mac Sequoia 15.0.1
