### ISSUE TITLE
I added Apple M1 (PyQt6) support!

### ISSUE THREAD

**Issue by guy4261** [rsusik/screenpen#9]
Hello,

Thanks for creating `screenpen`! It looked perfect for my needs.
It did not work on my Macbook Air M1 though, where PyQt5 has issues but PyQt6 works well.

So I ported the code and here is the fork, in case anyone ever needs it:

https://github.com/guy4261/screenpen

Thank you so much @rsusik !!! 🙇

**Comment by rsusik** [comment]
Thanks for these kind words. Nevertheless, what was the issue with PyQt5 on Mac? It looks like there is a PyQt5 distribution available for Mac: `PyQt5-5.15.9-cp37-abi3-macosx_10_13_x86_64.whl`
You may have installed both PyQt5 and PyQt6 (or PySide6) in your environment, which causes conflicts. There was a similar issue a while ago: https://github.com/rsusik/screenpen/issues/4.

**Comment by rsusik** [comment]
Closing
